package ar.edu.itba.paw.services;

public enum MatchUpdateFailureReason {
    MATCH_NOT_FOUND,
    FORBIDDEN,
    NOT_EDITABLE,
    NOT_RECURRING,
    INVALID_SCHEDULE,
    CAPACITY_BELOW_CONFIRMED,
    CAPACITY_ABOVE_MAX,
    PENDING_REQUESTS_EXCEED_AVAILABLE
}
