package ar.edu.itba.paw.services;

public enum TournamentBracketFailureReason {
    TOURNAMENT_NOT_FOUND,
    MATCH_NOT_FOUND,
    TEAM_NOT_FOUND,
    FORBIDDEN,
    NOT_READY_FOR_BRACKET,
    BRACKET_ALREADY_GENERATED,
    BRACKET_NOT_GENERATED,
    PAIRING_STRATEGY_REQUIRED,
    INVALID_PAIRINGS,
    MANUAL_PAIRINGS_REQUIRED,
    UNDER_CAPACITY,
    MISSING_MATCH_SCHEDULE,
    INVALID_SCHEDULE,
    SCHEDULE_BEFORE_NOW,
    INVALID_ROUND_ORDER,
    NOT_IN_PROGRESS,
    MATCH_NOT_READY,
    MATCH_ALREADY_DECIDED,
    WINNER_NOT_IN_MATCH,
    FORFEITING_TEAM_NOT_IN_MATCH
}
