CREATE TABLE player_reviews (
	id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	reviewer_user_id BIGINT NOT NULL REFERENCES users(id),
	reviewed_user_id BIGINT NOT NULL REFERENCES users(id),
	reaction VARCHAR(20) NOT NULL,
	comment CLOB,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP,
	CONSTRAINT ck_player_reviews_reaction CHECK (reaction IN ('like', 'dislike')),
	UNIQUE (reviewer_user_id, reviewed_user_id),
	CHECK (reviewer_user_id <> reviewed_user_id)
);

CREATE INDEX idx_player_reviews_reviewed_active
ON player_reviews(reviewed_user_id, deleted_at);

CREATE INDEX idx_player_reviews_reviewer_user_id
ON player_reviews(reviewer_user_id);
