-- HSQLDB-compatible schema for testing

CREATE TABLE users (
	id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	username VARCHAR(50) NOT NULL UNIQUE,
	name VARCHAR(150),
	last_name VARCHAR(150),
	email VARCHAR(255) NOT NULL UNIQUE,
	phone VARCHAR(50),
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE matches (
	id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	host_user_id BIGINT NOT NULL REFERENCES users(id),
	address VARCHAR(255) NOT NULL,
	title VARCHAR(150) NOT NULL,
	description CLOB,
	starts_at TIMESTAMP NOT NULL,
	ends_at TIMESTAMP,
	max_players INTEGER NOT NULL CHECK (max_players > 0),
	price_per_player NUMERIC(10,2) DEFAULT 0,
	visibility VARCHAR(20) NOT NULL DEFAULT 'public',
	status VARCHAR(20) NOT NULL DEFAULT 'draft',
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CHECK (ends_at IS NULL OR ends_at > starts_at)
);

CREATE INDEX idx_matches_host_user_id ON matches(host_user_id);

CREATE TABLE match_participants (
	id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	match_id BIGINT NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
	user_id BIGINT NOT NULL REFERENCES users(id),
	status VARCHAR(20) NOT NULL DEFAULT 'joined',
	joined_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UNIQUE (match_id, user_id)
);

CREATE TABLE tournaments (
	id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(150) NOT NULL,
	description CLOB,
	address VARCHAR(255) NOT NULL,
	host_user_id BIGINT NOT NULL REFERENCES users(id),
	format VARCHAR(30) NOT NULL,
	status VARCHAR(20) NOT NULL DEFAULT 'draft',
	starts_at TIMESTAMP,
	ends_at TIMESTAMP,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tournament_teams (
	id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	tournament_id BIGINT NOT NULL REFERENCES tournaments(id) ON DELETE CASCADE,
	name VARCHAR(150) NOT NULL,
	status VARCHAR(20) NOT NULL DEFAULT 'pending',
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UNIQUE (tournament_id, name)
);

CREATE TABLE tournament_team_members (
	id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	tournament_team_id BIGINT NOT NULL REFERENCES tournament_teams(id) ON DELETE CASCADE,
	user_id BIGINT NOT NULL REFERENCES users(id),
	status VARCHAR(20) NOT NULL DEFAULT 'joined',
	joined_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UNIQUE (tournament_team_id, user_id)
);

CREATE TABLE tournament_matches (
	id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	tournament_id BIGINT NOT NULL REFERENCES tournaments(id) ON DELETE CASCADE,
	match_id BIGINT NOT NULL REFERENCES matches(id),
	round_number INTEGER NOT NULL CHECK (round_number > 0),
	home_team_id BIGINT REFERENCES tournament_teams(id),
	away_team_id BIGINT REFERENCES tournament_teams(id),
	home_score INTEGER CHECK (home_score IS NULL OR home_score >= 0),
	away_score INTEGER CHECK (away_score IS NULL OR away_score >= 0),
	winner_team_id BIGINT REFERENCES tournament_teams(id),
	next_match_id BIGINT REFERENCES tournament_matches(id),
	winner_to_slot VARCHAR(10),
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
