CREATE TABLE email_action_requests (
	id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	action_type VARCHAR(50) NOT NULL,
	email VARCHAR(255) NOT NULL,
	user_id BIGINT REFERENCES users(id),
	token_hash VARCHAR(128) NOT NULL UNIQUE,
	payload_json CLOB NOT NULL,
	status VARCHAR(20) NOT NULL DEFAULT 'pending',
	expires_at TIMESTAMP NOT NULL,
	consumed_at TIMESTAMP,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT ck_email_action_type CHECK (action_type IN ('match_reservation')),
	CONSTRAINT ck_email_action_status CHECK (status IN ('pending', 'completed', 'failed', 'expired'))
);

CREATE INDEX idx_email_action_requests_email ON email_action_requests(email);
CREATE INDEX idx_email_action_requests_status ON email_action_requests(status);
